site_name: Where Sam learns Markdown

theme:
 name: simple-blog

nav:
  - Home: 'index.md'
  - Resume: 'resume.md'
  - Work samples: 'samples.md'

markdown_extensions:
  - attr_list

plugins:
  - mkdocs-pdf


