site_name: Where Sam learns Markdown

theme:
 name: readthedocs
 analytics:
 gtag: G-HD7X77HX1M

nav:
  - Home: 'index.md'
  - Resume: 'resume.md'
  - Work samples: 'samples.md'

markdown_extensions:
  - attr_list

plugins:
  - mkdocs-pdf


