site_name: Where Sam learns Markdown

theme:
 name: readthedocs
 custom_dir: custom_theme/
 titles_only: true
 

nav:
  - Home: 'index.md'
  - Resume: 'resume.md'
  - Work samples: 'samples.md'

markdown_extensions:
  - attr_list

plugins:
  - mkdocs-pdf


